include = ["cstdint","app.h"]
namespace="app"

[define]
NameMax=16
WorkMax=8

[struct]
name="parameter2"
maxsize=32

[[struct.member]]
name="name"
type="char"
default="--"
array="NameMax"
[[struct.member]]
name="age"
type="uint8_t"
default=16
[[struct.member]]
name="height"
type="float"
default=170.5
[[struct.member]]
name="grade"
type="uint8_t"
default="3"
[[struct.member]]
name="party"
type="uint8_t"
default="C"
