include = ["cstdint"]
namespace="app"

[struct]
name="parameter3"
maxsize=32

[[struct.member]]
name="state1"
type="unsigned"
bits=2
[[struct.member]]
name="state2"
type="unsigned"
bits=4
[[struct.member]]
name="state3"
type="unsigned"
bits=1
