[struct]
name="parameter3"
namespace="app"
maxsize=32
include = ["cstdint"]

[[member]]
name="state1"
type="unsigned"
bits=2
[[member]]
name="state2"
type="unsigned"
bits=4
[[member]]
name="state3"
type="unsigned"
bits=1
